version: "3.7"
services:
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    volumes:
        - ./gateway:/index
        - ${PWD}/index/node_modules
    depends_on:
      - bid
      - product
      - user
    stdin_open: true
  bid:
    build:
      context: ./bid
    container_name: bid
    ports:
      - "8001:8001"
    volumes:
        - ./bid:/index
        - ${PWD}/index/node_modules
    stdin_open: true
  product:
    build:
      context: ./product
    container_name: product
    ports:
      - "8002:8002"
    volumes:
        - ./product:/index
        - ${PWD}/index/node_modules
    stdin_open: true
  user:
    build:
      context: ./user
    container_name: user
    ports:
      - "8003:8003"
    volumes:
        - ./user:/index
        - ${PWD}/index/node_modules
    stdin_open: true
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
        - ./frontend:/index
        - ${PWD}/index/node_modules
    depends_on:
      - gateway
    stdin_open: true