version: "3.7"
services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "8000:8000"
    volumes:
        - ./gateway:/index
    depends_on:
      - bid
      - product
      - user
  bid:
    build:
      context: ./bid
    ports:
      - "8001:8001"
    volumes:
        - ./bid:/index

  product:
    build:
      context: ./product
    ports:
      - "8002:8002"
    volumes:
        - ./product:/index

  user:
    build:
      context: ./user
    ports:
      - "8003:8003"
    volumes:
        - ./user:/index

volumes:
  data:
  logs:

